name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up environment
        run: |
          echo "RAINBOW_MOCK_MODE=true" >> $GITHUB_ENV
          echo "LLM_PROVIDER=openai" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=sk-test-key-for-ci" >> $GITHUB_ENV
          echo "RAINBOW_DAILY_BUDGET=10.0" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PORT=9515" >> $GITHUB_ENV
          echo "RAINBOW_API_PORT=3001" >> $GITHUB_ENV
          echo "LOG_LEVEL=info" >> $GITHUB_ENV
          echo "RUST_LOG=info" >> $GITHUB_ENV
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: --shm-size=2gb
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
      - name: Set up environment
        run: |
          echo "RAINBOW_MOCK_MODE=true" >> $GITHUB_ENV
          echo "LLM_PROVIDER=openai" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=sk-test-key-for-ci" >> $GITHUB_ENV
          echo "RAINBOW_DAILY_BUDGET=10.0" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PORT=9515" >> $GITHUB_ENV
          echo "RAINBOW_API_PORT=3001" >> $GITHUB_ENV
          echo "LOG_LEVEL=info" >> $GITHUB_ENV
          echo "RUST_LOG=info" >> $GITHUB_ENV
          echo "CHROME_DRIVER_URL=http://localhost:4444" >> $GITHUB_ENV
          echo "CI=true" >> $GITHUB_ENV
          mkdir -p screenshots
      - name: Run tests
        run: cargo test --all-features --verbose

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: --shm-size=2gb
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Generate code coverage
        run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
        env:
          CHROME_DRIVER_URL: http://localhost:4444
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./cobertura.xml
          fail_ci_if_error: false

  benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run benchmarks
        run: cargo bench --no-default-features
        env:
          CI: true
      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmarks
          path: target/criterion

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./poc
          push: false
          tags: rainbow-poc:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    name: Release Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rainbow-poc-${{ matrix.os }}
          path: target/release/rainbow-poc*

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [check, test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
      - name: Set up environment
        run: |
          echo "RAINBOW_MOCK_MODE=true" >> $GITHUB_ENV
          echo "LLM_PROVIDER=openai" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=sk-test-key-for-ci" >> $GITHUB_ENV
          echo "RAINBOW_DAILY_BUDGET=10.0" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PORT=9515" >> $GITHUB_ENV
          echo "RAINBOW_API_PORT=3002" >> $GITHUB_ENV
          mkdir -p screenshots
      - name: Build
        run: cargo build --release
      - name: Start server in background
        run: |
          cargo run --release -- serve --port 3002 &
          echo $! > server.pid
          sleep 15  # Wait for server to start
      - name: Test health endpoint
        run: |
          curl -f http://localhost:3002/health
      - name: Test navigation API
        run: |
          curl -f -X POST http://localhost:3002/api/navigate \
            -H "Content-Type: application/json" \
            -d '{"url": "http://example.com", "take_screenshot": false}'
      - name: Test natural language API
        run: |
          curl -f -X POST http://localhost:3002/api/natural \
            -H "Content-Type: application/json" \
            -d '{"command": "navigate to example.com"}'
      - name: Test metrics endpoint
        run: |
          curl -f http://localhost:3002/metrics
      - name: Stop server
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
          fi