version: '3.8'

services:
  rainbow-poc:
    build: .
    container_name: rainbow-poc
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DAILY_BUDGET=${DAILY_BUDGET:-5.00}
      - RUST_LOG=${RUST_LOG:-info}
      - CHROME_DRIVER_URL=http://chromedriver:9515
    volumes:
      - ./screenshots:/app/screenshots
      - ./workflows:/app/workflows
      - ./data:/app/data
    depends_on:
      - chromedriver
    networks:
      - rainbow-net
    restart: unless-stopped
    command: ["rainbow-poc", "report"]

  chromedriver:
    image: selenium/standalone-chrome:latest
    container_name: rainbow-chromedriver
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=300
    ports:
      - "4444:4444"  # Selenium Grid UI
      - "7900:7900"  # VNC server for debugging
    shm_size: 2gb
    networks:
      - rainbow-net
    restart: unless-stopped

  # Optional: Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: rainbow-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - rainbow-net
    restart: unless-stopped

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: rainbow-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - rainbow-net
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  rainbow-net:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: